/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SXFS_H_RPCGEN
#define _SXFS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXIP 16
#define MAXSERVERS 10
#define MAXFILENAME 256
#define MAXFILES 20

typedef char *IP;

typedef char *filename;

typedef struct {
	u_int file_list_len;
	filename *file_list_val;
} file_list;

struct node {
	IP ip;
	int port;
};
typedef struct node node;

typedef struct {
	u_int server_list_len;
	node *server_list_val;
} server_list;

struct getload_1_argument {
	char *arg1;
	int arg2;
};
typedef struct getload_1_argument getload_1_argument;

#define SIMPLE_XFS 0x22221122
#define SIMPLE_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define FileFind 1
extern  server_list * filefind_1(char *, CLIENT *);
extern  server_list * filefind_1_svc(char *, struct svc_req *);
#define GetLoad 2
extern  int * getload_1(char *, int , CLIENT *);
extern  int * getload_1_svc(char *, int , struct svc_req *);
#define Download 3
extern  char ** download_1(char *, CLIENT *);
extern  char ** download_1_svc(char *, struct svc_req *);
#define UpdateList 4
extern  file_list * updatelist_1(CLIENT *);
extern  file_list * updatelist_1_svc(struct svc_req *);
extern int simple_xfs_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FileFind 1
extern  server_list * filefind_1();
extern  server_list * filefind_1_svc();
#define GetLoad 2
extern  int * getload_1();
extern  int * getload_1_svc();
#define Download 3
extern  char ** download_1();
extern  char ** download_1_svc();
#define UpdateList 4
extern  file_list * updatelist_1();
extern  file_list * updatelist_1_svc();
extern int simple_xfs_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_IP (XDR *, IP*);
extern  bool_t xdr_filename (XDR *, filename*);
extern  bool_t xdr_file_list (XDR *, file_list*);
extern  bool_t xdr_node (XDR *, node*);
extern  bool_t xdr_server_list (XDR *, server_list*);
extern  bool_t xdr_getload_1_argument (XDR *, getload_1_argument*);

#else /* K&R C */
extern bool_t xdr_IP ();
extern bool_t xdr_filename ();
extern bool_t xdr_file_list ();
extern bool_t xdr_node ();
extern bool_t xdr_server_list ();
extern bool_t xdr_getload_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SXFS_H_RPCGEN */
