/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sxfs.h"


void
simple_xfs_1(char *host)
{
	CLIENT *clnt;
	client_list  *result_1;
	char *file_find_1_arg1;
	int  *result_2;
	char *get_load_1_arg1;
	int get_load_1_arg2;
	char * *result_3;
	char *download_1_arg1;
	files_in_client  *result_4;
	int  *result_5;
	IP join_client_1_arg1;
	int join_client_1_arg2;

#ifndef	DEBUG
	clnt = clnt_create (host, SIMPLE_XFS, SIMPLE_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = file_find_1(file_find_1_arg1, clnt);
	if (result_1 == (client_list *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = get_load_1(get_load_1_arg1, get_load_1_arg2, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = download_1(download_1_arg1, clnt);
	if (result_3 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = update_list_1(clnt);
	if (result_4 == (files_in_client *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = join_client_1(join_client_1_arg1, join_client_1_arg2, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	simple_xfs_1 (host);
exit (0);
}
