/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sxfs.h"

server_list *
filefind_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static server_list  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
getload_1_svc(char *arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
download_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

file_list *
updatelist_1_svc(struct svc_req *rqstp)
{
	static file_list  result;

	/*
	 * insert server code here
	 */

	return &result;
}
